### ISSUE TITLE
Lier les deux pages de visualisation

### ISSUE THREAD

**Issue by ipante** [rob1unil/Switzerland-medals-at-the-olympics#3]
Il doit être possible de passer d'une page à l'autre en cliquant sur un lien. Vous pouvez choisir
1. soit de créer une page initiale (index.html) qui conduise vers chaque page
2. soit créer un lien vers l'autre page depuis chaque page

**Comment by rob1unil** [comment]
Les liens ont été ajoutés. Il maintenant possible de naviguer entre les deux pages.
